### ISSUE TITLE
No stache folder causes stache search scraper to fail

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/stache2#388]
I have installed Stache as a dependency, but not created a Stache folder.  That's caused the `e2e` step to fail.

```
2018-01-11T20:50:16.2345138Z Failures:
2018-01-11T20:50:16.2345138Z 1) Search Results should generate search results
2018-01-11T20:50:16.2345138Z   Message:
2018-01-11T20:50:16.2345138Z [31m    Expected Error: ENOENT: no such file or directory, mkdir 'C:\vsts-agent-win7-x64-2.111.1_2\_work\1883\s\src\stache\search' to be null.[0m
2018-01-11T20:50:16.2345138Z   Stack:
2018-01-11T20:50:16.2345138Z     Error: Failed expectation
2018-01-11T20:50:16.2345138Z         at C:\vsts-agent-win7-x64-2.111.1_2\_work\1883\s\e2e\stache-search.e2e-spec.ts:172:23
2018-01-11T20:50:16.2345138Z         at process._tickCallback (internal/process/next_tick.js:103:7)
2018-01-11T20:50:16.2345138Z 
2018-01-11T20:50:16.2345138Z 1 spec, 1 failure
2018-01-11T20:50:16.2345138Z Finished in 5.824 seconds
```

**Comment by Blackbaud-LindseyRix** [comment]
Resolved by @blackbaud-brandonhare . For details, please speak with him.
